/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteDeveloperHyderabadRouteImport } from './routes/website-developer-hyderabad'
import { Route as WebDesignerHyderabadRouteImport } from './routes/web-designer-hyderabad'
import { Route as SmallBusinessWebsiteHyderabadRouteImport } from './routes/small-business-website-hyderabad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductCatalogWebsitesHyderabadRouteImport } from './routes/product-catalog-websites-hyderabad'
import { Route as EcommerceWebsiteDevelopmentHyderabadRouteImport } from './routes/ecommerce-website-development-hyderabad'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiconsultationRouteImport } from './routes/aiconsultation'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicFeedbackSubmitRouteImport } from './routes/api/public/feedback-submit'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WebsiteDeveloperHyderabadRoute =
  WebsiteDeveloperHyderabadRouteImport.update({
    id: '/website-developer-hyderabad',
    path: '/website-developer-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebDesignerHyderabadRoute = WebDesignerHyderabadRouteImport.update({
  id: '/web-designer-hyderabad',
  path: '/web-designer-hyderabad',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallBusinessWebsiteHyderabadRoute =
  SmallBusinessWebsiteHyderabadRouteImport.update({
    id: '/small-business-website-hyderabad',
    path: '/small-business-website-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCatalogWebsitesHyderabadRoute =
  ProductCatalogWebsitesHyderabadRouteImport.update({
    id: '/product-catalog-websites-hyderabad',
    path: '/product-catalog-websites-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcommerceWebsiteDevelopmentHyderabadRoute =
  EcommerceWebsiteDevelopmentHyderabadRouteImport.update({
    id: '/ecommerce-website-development-hyderabad',
    path: '/ecommerce-website-development-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiconsultationRoute = AiconsultationRouteImport.update({
  id: '/aiconsultation',
  path: '/aiconsultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackSubmitRoute = ApiPublicFeedbackSubmitRouteImport.update({
  id: '/api/public/feedback-submit',
  path: '/api/public/feedback-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiconsultation': typeof AiconsultationRoute
  '/auth': typeof AuthRoute
  '/ecommerce-website-development-hyderabad': typeof EcommerceWebsiteDevelopmentHyderabadRoute
  '/product-catalog-websites-hyderabad': typeof ProductCatalogWebsitesHyderabadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-business-website-hyderabad': typeof SmallBusinessWebsiteHyderabadRoute
  '/web-designer-hyderabad': typeof WebDesignerHyderabadRoute
  '/website-developer-hyderabad': typeof WebsiteDeveloperHyderabadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/feedback-submit': typeof ApiPublicFeedbackSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiconsultation': typeof AiconsultationRoute
  '/auth': typeof AuthRoute
  '/ecommerce-website-development-hyderabad': typeof EcommerceWebsiteDevelopmentHyderabadRoute
  '/product-catalog-websites-hyderabad': typeof ProductCatalogWebsitesHyderabadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-business-website-hyderabad': typeof SmallBusinessWebsiteHyderabadRoute
  '/web-designer-hyderabad': typeof WebDesignerHyderabadRoute
  '/website-developer-hyderabad': typeof WebsiteDeveloperHyderabadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/feedback-submit': typeof ApiPublicFeedbackSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aiconsultation': typeof AiconsultationRoute
  '/auth': typeof AuthRoute
  '/ecommerce-website-development-hyderabad': typeof EcommerceWebsiteDevelopmentHyderabadRoute
  '/product-catalog-websites-hyderabad': typeof ProductCatalogWebsitesHyderabadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-business-website-hyderabad': typeof SmallBusinessWebsiteHyderabadRoute
  '/web-designer-hyderabad': typeof WebDesignerHyderabadRoute
  '/website-developer-hyderabad': typeof WebsiteDeveloperHyderabadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/feedback-submit': typeof ApiPublicFeedbackSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiconsultation'
    | '/auth'
    | '/ecommerce-website-development-hyderabad'
    | '/product-catalog-websites-hyderabad'
    | '/sitemap.xml'
    | '/small-business-website-hyderabad'
    | '/web-designer-hyderabad'
    | '/website-developer-hyderabad'
    | '/admin'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/portfolio/$id'
    | '/api/public/contact-submit'
    | '/api/public/feedback-submit'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiconsultation'
    | '/auth'
    | '/ecommerce-website-development-hyderabad'
    | '/product-catalog-websites-hyderabad'
    | '/sitemap.xml'
    | '/small-business-website-hyderabad'
    | '/web-designer-hyderabad'
    | '/website-developer-hyderabad'
    | '/admin'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/portfolio/$id'
    | '/api/public/contact-submit'
    | '/api/public/feedback-submit'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aiconsultation'
    | '/auth'
    | '/ecommerce-website-development-hyderabad'
    | '/product-catalog-websites-hyderabad'
    | '/sitemap.xml'
    | '/small-business-website-hyderabad'
    | '/web-designer-hyderabad'
    | '/website-developer-hyderabad'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/portfolio/$id'
    | '/api/public/contact-submit'
    | '/api/public/feedback-submit'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiconsultationRoute: typeof AiconsultationRoute
  AuthRoute: typeof AuthRoute
  EcommerceWebsiteDevelopmentHyderabadRoute: typeof EcommerceWebsiteDevelopmentHyderabadRoute
  ProductCatalogWebsitesHyderabadRoute: typeof ProductCatalogWebsitesHyderabadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmallBusinessWebsiteHyderabadRoute: typeof SmallBusinessWebsiteHyderabadRoute
  WebDesignerHyderabadRoute: typeof WebDesignerHyderabadRoute
  WebsiteDeveloperHyderabadRoute: typeof WebsiteDeveloperHyderabadRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  ApiPublicFeedbackSubmitRoute: typeof ApiPublicFeedbackSubmitRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-developer-hyderabad': {
      id: '/website-developer-hyderabad'
      path: '/website-developer-hyderabad'
      fullPath: '/website-developer-hyderabad'
      preLoaderRoute: typeof WebsiteDeveloperHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-designer-hyderabad': {
      id: '/web-designer-hyderabad'
      path: '/web-designer-hyderabad'
      fullPath: '/web-designer-hyderabad'
      preLoaderRoute: typeof WebDesignerHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-business-website-hyderabad': {
      id: '/small-business-website-hyderabad'
      path: '/small-business-website-hyderabad'
      fullPath: '/small-business-website-hyderabad'
      preLoaderRoute: typeof SmallBusinessWebsiteHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-catalog-websites-hyderabad': {
      id: '/product-catalog-websites-hyderabad'
      path: '/product-catalog-websites-hyderabad'
      fullPath: '/product-catalog-websites-hyderabad'
      preLoaderRoute: typeof ProductCatalogWebsitesHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-website-development-hyderabad': {
      id: '/ecommerce-website-development-hyderabad'
      path: '/ecommerce-website-development-hyderabad'
      fullPath: '/ecommerce-website-development-hyderabad'
      preLoaderRoute: typeof EcommerceWebsiteDevelopmentHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiconsultation': {
      id: '/aiconsultation'
      path: '/aiconsultation'
      fullPath: '/aiconsultation'
      preLoaderRoute: typeof AiconsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback-submit': {
      id: '/api/public/feedback-submit'
      path: '/api/public/feedback-submit'
      fullPath: '/api/public/feedback-submit'
      preLoaderRoute: typeof ApiPublicFeedbackSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiconsultationRoute: AiconsultationRoute,
  AuthRoute: AuthRoute,
  EcommerceWebsiteDevelopmentHyderabadRoute:
    EcommerceWebsiteDevelopmentHyderabadRoute,
  ProductCatalogWebsitesHyderabadRoute: ProductCatalogWebsitesHyderabadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmallBusinessWebsiteHyderabadRoute: SmallBusinessWebsiteHyderabadRoute,
  WebDesignerHyderabadRoute: WebDesignerHyderabadRoute,
  WebsiteDeveloperHyderabadRoute: WebsiteDeveloperHyderabadRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  ApiPublicFeedbackSubmitRoute: ApiPublicFeedbackSubmitRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
